services:
  mimir:
    image: grafana/mimir:2.12.0
    container_name: mimir
    #expose:
    #  - 9090
    restart: unless-stopped
    command: --config.file=/etc/mimir.yaml
    volumes:
      - ./services/mimir/mimir.yaml:/etc/mimir.yaml
      - ./services/mimir/alertmanager.yaml:/etc/alertmanager-fallback-config.yaml

  loki:
    image: grafana/loki:3.1.0
    container_name: loki
    #expose:
    #  - 3100
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./services/loki/loki-config.yaml:/etc/loki/loki-config.yaml
    environment:
      - JAEGER_AGENT_HOST=${JAEGER_AGENT_HOST}

  grafana:
    image: grafana/grafana:11.0.1
    container_name: grafana
    restart: unless-stopped
    expose:
       - 3000
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD}
      - GF_SECURITY_ALLOW_EMBEDDING=${GF_SECURITY_ALLOW_EMBEDDING}
    volumes:
      - ./services/grafana/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      # - ./services/grafana/grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - loki
      - tempo
      - mimir

  tempo:
    image: grafana/tempo:2.5.0
    container_name: tempo
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./services/tempo/tempo.yaml:/etc/tempo.yaml

  ## Tools
  promtail:
    image: grafana/promtail:2.9.5
    container_name: promtail
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml

  otelcol:
    image: otel/opentelemetry-collector-contrib:0.141.0
    container_name: otelcol
    # restart: unless-stopped
    ports:
       - 4317:4317
       - 4318:4318
    command: --config=/etc/otel.yaml
    depends_on:
      - loki
      - tempo
      - mimir
      - grafana
    environment:
      - OTLP_TOKEN=${OTLP_TOKEN}
    volumes:
      - ./services/otelcol/config.yaml:/etc/otel.yaml
