extensions:
  bearertokenauth:
    token: ${env:OTLP_TOKEN}
  health_check:
  pprof:
  zpages:
    
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        auth:
          authenticator: bearertokenauth
      http:
        auth:
          authenticator: bearertokenauth
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
        - job_name: "otel-collector"
          scrape_interval: 60s
          static_configs:
            - targets: ["localhost:8888"]
  hostmetrics:
    # Tell the scrapers to look at the mounted volume, not the container's /
    root_path: /hostfs
    collection_interval: 1m # Default is 1m, adjust based on resolution needs
    scrapers:
      cpu:
      memory:
      load:
      network:
      disk:
      filesystem:
processors:
  batch:

exporters:
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

  prometheusremotewrite:
    endpoint: http://mimir:9090/api/v1/push

service:
  extensions: [health_check, pprof, zpages, bearertokenauth]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo]
    metrics:
      receivers: [otlp, prometheus,hostmetrics]
      processors: [batch]
      exporters: [prometheusremotewrite]
